codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down

  status:
    project:
      default:
        threshold: 1
    patch:
      default:
        threshold: 1
    changes: off
