repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: trailing-whitespace
    exclude: README.md

- repo: https://github.com/ambv/black
  rev: 21.4b0
  hooks:
  - id: black
    name: Blacken

- repo: local
  hooks:
  - id: codecov-validator
    name: Validate .codecov.yml
    description: Validate .codecov.yml using codecov's online validation tool.
    entry: ./.ci/codecov_validator.sh
    files: >
      (?x)^(
        .codecov.yml
      )$
    language: system

- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.1'
  hooks:
  - id: flake8
    args: [--count, --show-source, --statistics]
