repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: trailing-whitespace
    exclude: README.md

- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    name: Blacken

- repo: local
  hooks:
  - id: codecov-validator
    name: Validate .codecov.yml
    description: Validate .codecov.yml using codecov's online validation tool.
    entry: ./.ci/codecov_validator.sh
    files: >
      (?x)^(
        .codecov.yml
      )$
    language: system
