name: CD - Publish on PyPI

on:
  release:
    types:
      - published

jobs:
  publish:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/cd_release.yml@v2.5.1
    if: github.repository == 'CasperWA/voila-optimade-client' && startsWith(github.ref, 'refs/tags/20')
    with:
      # General
      git_username: CasperWA
      git_email: "casper+github@welzel.nu"
      release_branch: develop
      install_extras: "[dev]"

      # PyPI publication
      python_package: true
      python_version_build: "3.9"
      package_dirs: "optimade_client"
      version_update_changes_separator: ";"
      version_update_changes: |
        optimade_client/__init__.py;__version__ = .+;__version__ = "{version}"
        setup.py;version=([^,]+),;version="{version}",
        optimade_client/informational.py;Client version.*</code>;Client version</b>: <code>{version}</code>
        optimade_client/cli/run.py;VERSION = \".+\";VERSION = "{version}"
      build_libs: "build"
      build_cmd: "python -m build"
      publish_on_pypi: true

      # Documentation
      update_docs: false
    secrets:
      PyPI_token: ${{ secrets.pypi_password }}
      PAT: ${{ secrets.RELEASE_PAT }}

  update-stable:
    name: Update `stable` branch
    needs: publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: stable
        persist-credentials: false

    - name: Setup git config
      run: |
        git config --global user.name "CasperWA"
        git config --global user.email "casper+github@welzel.nu"

    - name: Make `stable` branch equal to `develop` branch
      run: git merge --ff-only origin/develop

    - name: Update `stable` branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.RELEASE_PAT }}
        branch: stable
