name: CI - Single Dependabot PR

on:
  schedule:
    # At 8:30 every Wednesday (6:30 UTC)
    # Dependabot runs once a week (every Monday) (pip)
    # and every day (GH Actions) at 7:00 (5:00 UTC)
    - cron: "30 6 * * 3"
  workflow_dispatch:

jobs:
  create-collected-pr:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_update_dependencies.yml@v2.7.2
    if: github.repository_owner == 'CasperWA'

    with:
      # General
      git_username: CasperWA
      git_email: "casper+github@welzel.nu"
      permanent_dependencies_branch: ci/dependabot-updates
      default_repo_branch: develop

      # Generated PR
      pr_labels: github_actions,dependencies

      # pre-commit
      update_pre-commit: true
      python_version: "3.9"
      install_extras: "[dev]"
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
