name: CI - Tests

on:
  pull_request:
  push:
    branches:
      - develop
      - stable
      - 'push-action/**'

jobs:
  basic_tests:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_tests.yml@v2.6.0
    with:
      # General
      install_extras: "[dev]"

      # pre-commit
      run_pre-commit: true
      python_version_pre-commit: "3.9"
      skip_pre-commit_hooks: pylint

      # pylint & safety
      run_pylint: false
      run_safety: false

      # Build package
      run_build_package: true
      python_version_package: "3.9"
      build_libs: build
      build_cmd: "python -m build"

      # Build documentation
      run_build_docs: false

  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version}}

    - name: Install initial dependencies
      run: |
        python -m pip install -U pip
        pip install -U setuptools wheel
        pip install -e .[testing]

    - name: PyTest
      run: pytest -vvv --cov=optimade_client --cov-report=xml --cov-append tests/

    - name: Install server dependencies
      run: pip install -e .[server]

    - name: PyTest (with 'server' extra)
      run: pytest --cov=optimade_client --cov-report=xml --cov-append tests/cli/

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.9' && github.repository == 'CasperWA/voila-optimade-client'
      uses: codecov/codecov-action@v3
      with:
        name: optimade-client
        file: ./coverage.xml
        flags: optimade-client
