name: CI - Update dependabot branch

on:
  push:
    branches: [develop]

jobs:
  update-dependabot-branch:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_cd_updated_default_branch.yml@v2.5.0
    if: github.repository_owner == 'CasperWA'
    with:
      # General
      git_username: CasperWA
      git_email: "casper+github@welzel.nu"
      default_repo_branch: develop

      # Dependabot branch
      permanent_dependencies_branch: ci/dependabot-updates

      # Documentation
      update_docs: false
    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
