name: Publish on PyPI

on:
  push:
    tags:
      - 20[2-9][0-9].?[0-9].?[0-9]*

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'CasperWA/voila-optimade-client' && startsWith(github.ref, 'refs/tags/20')

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install -U invoke

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Assert package version
      run: |
        invoke update-version --version="${GITHUB_REF#refs/tags/}"
        if [ -n "$(git status --porcelain --untracked-files=no --ignored=no)" ]; then
          echo "It seems updating the version to ${GITHUB_REF#refs/tags/} results in modified files in the repository."
          git status
          exit 1
        fi

    - name: Build source distribution
      run: python ./setup.py sdist

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
